import { NextRequest,NextResponse } from 'next/server'
import { neon } from '@neondatabase/serverless'
const COOKIE='cv_session',ALL=['dashboard','services','clients','production','finance','catalog','stock','settings','team']
const ROLE:Record<string,string[]>={owner:ALL,admin:ALL,commercial:['dashboard','services','clients','catalog'],production:['dashboard','services','production','stock'],finance:['dashboard','finance'],stock:['dashboard','stock'],member:['dashboard']}
const publicPrefix=['/login','/setup','/convite','/orcamento','/cobranca','/api/auth','/api/cnpj','/api/quote-public','/api/health','/_next','/favicon.ico']
const isPublic=(p:string)=>publicPrefix.some(x=>p===x||p.startsWith(x+'/'))
const required=(p:string,method:string)=>p.startsWith('/api/platform')?'SUPER':p.startsWith('/api/team')?'team':p.startsWith('/api/company-settings')?(method==='GET'?'dashboard':'settings'):p.startsWith('/api/pricing-settings')?'settings':p.startsWith('/api/finance')?'finance':p.startsWith('/api/materials')||p.startsWith('/api/stock-invoice')?'stock':p.startsWith('/api/catalog')?'catalog':p.startsWith('/api/clients')?'clients':p.startsWith('/api/tasks')||p.startsWith('/api/installation')?'production':p.startsWith('/api/services')||p.startsWith('/api/quote-items')||p.startsWith('/api/quote-print')||p.startsWith('/api/quote-share')||p.startsWith('/api/artworks')||p.startsWith('/api/work-order-events')||p.startsWith('/api/work-order-result')?'services':p.startsWith('/api/dashboard')?'dashboard':null
async function sha256(v:string){const data=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(data)).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function middleware(req:NextRequest){const path=req.nextUrl.pathname;if(isPublic(path)){if(path.startsWith('/orcamento')||path.startsWith('/api/quote-public')){const h=new Headers(req.headers);h.set('x-public-company-bootstrap','1');return NextResponse.next({request:{headers:h}})}return NextResponse.next()}const raw=req.cookies.get(COOKIE)?.value;if(!raw){if(path.startsWith('/api/'))return NextResponse.json({error:'Não autenticado'},{status:401});const u=req.nextUrl.clone();u.pathname='/login';u.searchParams.set('next',path);return NextResponse.redirect(u)}try{const url=process.env.DATABASE_URL;if(!url)throw new Error('db');const sql=neon(url),tokenHash=await sha256(raw);const rows=await sql`select s.user_id,s.company_id,u.is_super_admin,cu.role,cu.permissions,c.status company_status from user_sessions s join app_users u on u.id=s.user_id and u.status='active' join companies c on c.id=s.company_id left join company_users cu on cu.user_id=u.id and cu.company_id=s.company_id and cu.active=true where s.token_hash=${tokenHash} and s.expires_at>now() and (u.is_super_admin=true or cu.id is not null) limit 1`;if(!rows.length||rows[0].company_status!=='active')throw new Error('invalid');const x=rows[0],superAdmin=!!x.is_super_admin,perms=superAdmin?ALL:Array.from(new Set([...(ROLE[String(x.role||'member')]||ROLE.member),...(Array.isArray(x.permissions)?x.permissions.map(String):[])])),need=required(path,req.method);if((need==='SUPER'&&!superAdmin)||(need&&need!=='SUPER'&&!perms.includes(need)))return NextResponse.json({error:'Sem permissão para esta área'},{status:403});const h=new Headers(req.headers);h.set('x-user-id',String(x.user_id));h.set('x-company-id',String(x.company_id));h.set('x-role',String(x.role||'member'));h.set('x-permissions',perms.join(','));h.set('x-super-admin',superAdmin?'1':'0');return NextResponse.next({request:{headers:h}})}catch{if(path.startsWith('/api/'))return NextResponse.json({error:'Sessão expirada'},{status:401});const u=req.nextUrl.clone();u.pathname='/login';u.searchParams.set('expired','1');const res=NextResponse.redirect(u);res.cookies.delete(COOKIE);return res}}
export const config={matcher:['/((?!_next/static|_next/image).*)']}
