'use client'
import { useEffect,useState } from 'react'
export default function Plataforma(){
 const [companies,setCompanies]=useState<any[]>([]),[form,setForm]=useState({name:'',ownerEmail:'',plan:'professional',userLimit:'10'}),[msg,setMsg]=useState(''),[invite,setInvite]=useState('')
 async function load(){const mr=await fetch('/api/auth/me',{cache:'no-store'});if(mr.status===401){location.href='/login';return}const me=await mr.json();if(!me.isSuperAdmin){location.href='/';return}const r=await fetch('/api/platform/companies',{cache:'no-store'});if(r.ok)setCompanies(await r.json())}
 useEffect(()=>{load()},[])
 async function create(){setMsg('Criando empresa...');setInvite('');const r=await fetch('/api/platform/companies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,userLimit:Number(form.userLimit)})}),x=await r.json().catch(()=>({}));if(!r.ok){setMsg(x.error||'Erro ao criar empresa.');return}setMsg('Empresa criada. Envie o link ao proprietário.');setInvite(x.inviteUrl||'');setForm({name:'',ownerEmail:'',plan:'professional',userLimit:'10'});await load()}
 async function save(c:any){const r=await fetch('/api/platform/companies',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:c.id,status:c.status,plan:c.plan,userLimit:Number(c.user_limit)})});setMsg(r.ok?'Empresa atualizada.':'Erro ao atualizar empresa.');if(r.ok)await load()}
 async function enter(companyId:string){const r=await fetch('/api/auth/switch-company',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId})});if(r.ok)location.href='/'}
 return <main className="manageShell"><header className="manageHeader"><div><span>ADMINISTRAÇÃO DA PLATAFORMA</span><h1>Empresas clientes</h1><p>Crie ambientes isolados, controle planos, usuários e acesso.</p></div><a href="/">← Voltar ao sistema</a></header><section className="manageGrid"><div className="panel manageCard"><div className="panelTitle"><div><h3>Nova empresa</h3><p>O proprietário receberá um link de primeiro acesso.</p></div></div><label>Empresa<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>E-mail do proprietário<input type="email" value={form.ownerEmail} onChange={e=>setForm({...form,ownerEmail:e.target.value})}/></label><label>Plano<select value={form.plan} onChange={e=>setForm({...form,plan:e.target.value})}><option value="starter">Inicial</option><option value="professional">Profissional</option><option value="business">Empresa</option></select></label><label>Limite de usuários<input type="number" min="1" value={form.userLimit} onChange={e=>setForm({...form,userLimit:e.target.value})}/></label><button className="primary wide" onClick={create}>Criar empresa</button>{msg&&<div className="clientMsg">{msg}</div>}{invite&&<div className="inviteLinkBox"><input readOnly value={invite}/><button onClick={()=>navigator.clipboard?.writeText(invite)}>Copiar primeiro acesso</button></div>}</div><div className="panel manageCard wideCard"><div className="panelTitle"><div><h3>Empresas cadastradas</h3><p>{companies.length} ambiente(s) na plataforma.</p></div><button onClick={load}>Atualizar</button></div>{companies.map((c:any)=><div className="companyAdminRow" key={c.id}><div><b>{c.name}</b><span>{c.slug} · {c.users} usuário(s)</span></div><select value={c.plan} onChange={e=>setCompanies(a=>a.map(x=>x.id===c.id?{...x,plan:e.target.value}:x))}><option value="starter">Inicial</option><option value="professional">Profissional</option><option value="business">Empresa</option></select><input type="number" min="1" value={c.user_limit} onChange={e=>setCompanies(a=>a.map(x=>x.id===c.id?{...x,user_limit:e.target.value}:x))}/><select value={c.status} onChange={e=>setCompanies(a=>a.map(x=>x.id===c.id?{...x,status:e.target.value}:x))}><option value="active">Ativa</option><option value="blocked">Bloqueada</option></select><div><button onClick={()=>save(c)}>Salvar</button><button onClick={()=>enter(c.id)}>Entrar</button></div></div>)}</div></section></main>
}
