import { NextResponse } from 'next/server'
import { ensureSchema } from '@/lib/bootstrap'
import { ALL_PERMISSIONS,getAuthContext,hashToken,newOpaqueToken,ROLE_LABELS } from '@/lib/auth'
import { getDb } from '@/lib/db'
const roles=['admin','commercial','production','finance','stock','member','custom']
async function context(){await ensureSchema();const c=await getAuthContext();if(!c||!c.permissions.includes('team'))return null;return c}
export async function GET(){const c=await context();if(!c)return NextResponse.json({error:'Sem permissão'},{status:403});const sql=getDb();const members=await sql`select cu.id,cu.user_id,u.name,u.email,cu.role,cu.permissions,cu.active,u.last_login_at,cu.created_at from company_users cu join app_users u on u.id=cu.user_id where cu.company_id=${c.companyId} order by case when cu.role='owner' then 0 else 1 end,u.name`;const invites=await sql`select id,email,role,permissions,expires_at,created_at from company_invites where company_id=${c.companyId} and accepted_at is null and expires_at>now() order by created_at desc`;return NextResponse.json({members,invites,permissions:ALL_PERMISSIONS,roleLabels:ROLE_LABELS})}
export async function POST(req:Request){const c=await context();if(!c)return NextResponse.json({error:'Sem permissão'},{status:403});const sql=getDb(),b=await req.json(),email=String(b.email||'').trim().toLowerCase(),role=roles.includes(String(b.role))?String(b.role):'member',permissions=Array.isArray(b.permissions)?b.permissions.map(String).filter((x:string)=>(ALL_PERMISSIONS as readonly string[]).includes(x)):[];if(!/^\S+@\S+\.\S+$/.test(email))return NextResponse.json({error:'E-mail inválido'},{status:400});const company=await sql`select user_limit from companies where id=${c.companyId}`,counts=await sql`select (select count(*) from company_users where company_id=${c.companyId} and active=true)+(select count(*) from company_invites where company_id=${c.companyId} and accepted_at is null and expires_at>now()) n`;if(Number(counts[0]?.n||0)>=Number(company[0]?.user_limit||10))return NextResponse.json({error:'Limite de usuários do plano atingido.'},{status:409});const token=newOpaqueToken();await sql`delete from company_invites where company_id=${c.companyId} and lower(email)=${email} and accepted_at is null`;await sql`insert into company_invites(company_id,email,role,permissions,token_hash,expires_at,invited_by) values(${c.companyId},${email},${role},${permissions},${hashToken(token)},now()+interval '7 days',${c.userId})`;return NextResponse.json({ok:true,inviteUrl:new URL('/convite/'+token,req.url).toString()})}
export async function PATCH(req:Request){const c=await context();if(!c)return NextResponse.json({error:'Sem permissão'},{status:403});const sql=getDb(),b=await req.json(),memberId=String(b.memberId||''),role=roles.includes(String(b.role))?String(b.role):'member',permissions=Array.isArray(b.permissions)?b.permissions.map(String).filter((x:string)=>(ALL_PERMISSIONS as readonly string[]).includes(x)):[],active=b.active!==false;const target=await sql`select id,role,user_id from company_users where id=${memberId} and company_id=${c.companyId} limit 1`;if(!target.length)return NextResponse.json({error:'Usuário não encontrado'},{status:404});if(target[0].role==='owner'&&(!active||role!=='owner')){const owners=await sql`select count(*)::int n from company_users where company_id=${c.companyId} and role='owner' and active=true`;if(Number(owners[0].n)<=1)return NextResponse.json({error:'A empresa precisa manter ao menos um proprietário ativo.'},{status:409})}await sql`update company_users set role=${role},permissions=${permissions},active=${active},updated_at=now() where id=${memberId} and company_id=${c.companyId}`;return NextResponse.json({ok:true})}
export async function DELETE(req:Request){const c=await context();if(!c)return NextResponse.json({error:'Sem permissão'},{status:403});const sql=getDb(),b=await req.json();if(b.inviteId){await sql`delete from company_invites where id=${String(b.inviteId)} and company_id=${c.companyId} and accepted_at is null`;return NextResponse.json({ok:true})}const memberId=String(b.memberId||''),target=await sql`select role,user_id from company_users where id=${memberId} and company_id=${c.companyId}`;if(!target.length)return NextResponse.json({error:'Usuário não encontrado'},{status:404});if(String(target[0].user_id)===c.userId)return NextResponse.json({error:'Você não pode remover seu próprio acesso por aqui.'},{status:409});if(target[0].role==='owner'){const owners=await sql`select count(*)::int n from company_users where company_id=${c.companyId} and role='owner' and active=true`;if(Number(owners[0].n)<=1)return NextResponse.json({error:'A empresa precisa manter um proprietário.'},{status:409})}await sql`delete from company_users where id=${memberId} and company_id=${c.companyId}`;return NextResponse.json({ok:true})}
