import { NextResponse } from 'next/server'
import { getDb } from '@/lib/db'
import { ensureDb } from '@/lib/bootstrap'
export const dynamic='force-dynamic'

export async function GET(req:Request){
 try{const companyId=await ensureDb();const sql=getDb();const id=new URL(req.url).searchParams.get('workOrderId');if(!id)return NextResponse.json({error:'OS obrigatória'},{status:400});const rows=await sql`select i.* from work_order_items i join work_orders w on w.id=i.work_order_id where i.work_order_id=${id} and w.company_id=${companyId} order by i.created_at`;return NextResponse.json(rows)}
 catch{return NextResponse.json({error:'Erro ao carregar itens'},{status:500})}
}
export async function POST(req:Request){
 try{const companyId=await ensureDb();const sql=getDb();const b=await req.json();if(!b.workOrderId||!String(b.description||'').trim())return NextResponse.json({error:'Descrição obrigatória'},{status:400});const os=await sql`select id from work_orders where id=${b.workOrderId} and company_id=${companyId} limit 1`;if(!os.length)return NextResponse.json({error:'OS não encontrada'},{status:404});const q=Math.max(Number(b.quantity)||1,0);const p=Math.max(Number(b.unitPrice)||0,0);const rows=await sql`insert into work_order_items(work_order_id,description,quantity,unit,unit_price) values(${b.workOrderId},${String(b.description).trim()},${q},${b.unit||'un'},${p}) returning *`;if(b.catalogId){const cat=await sql`select production_hours_per_unit,installation_hours_per_unit,machine_hours_per_unit from service_catalog where id=${b.catalogId} and (company_id is null or company_id=${companyId})`;if(cat.length){const ph=q*Number(cat[0].production_hours_per_unit||0),ih=q*Number(cat[0].installation_hours_per_unit||0),mh=q*Number(cat[0].machine_hours_per_unit||0);await sql`update work_orders set production_hours=production_hours+${ph},installation_hours=installation_hours+${ih},machine_hours=machine_hours+${mh} where id=${b.workOrderId} and company_id=${companyId}`}const tech=await sql`select scm.material_id,scm.consumption_per_unit,scm.waste_percent from service_catalog_materials scm join service_catalog sc on sc.id=scm.service_catalog_id where scm.service_catalog_id=${b.catalogId} and (sc.company_id is null or sc.company_id=${companyId})`;for(const t of tech){const need=q*Number(t.consumption_per_unit)*(1+Number(t.waste_percent)/100);await sql`insert into work_order_materials(work_order_id,material_id,quantity) values(${b.workOrderId},${t.material_id},${need}) on conflict(work_order_id,material_id) do update set quantity=work_order_materials.quantity+excluded.quantity`}}await sql`update work_orders set total=(select coalesce(sum(quantity*unit_price),0) from work_order_items where work_order_id=${b.workOrderId}) where id=${b.workOrderId} and company_id=${companyId}`;return NextResponse.json(rows[0],{status:201})}
 catch{return NextResponse.json({error:'Erro ao adicionar item'},{status:500})}
}
export async function DELETE(req:Request){
 try{const companyId=await ensureDb();const sql=getDb();const b=await req.json();const found=await sql`select i.work_order_id from work_order_items i join work_orders w on w.id=i.work_order_id where i.id=${b.id} and w.company_id=${companyId} limit 1`;if(!found.length)return NextResponse.json({error:'Item não encontrado'},{status:404});const workOrderId=found[0].work_order_id;await sql`delete from work_order_items where id=${b.id}`;await sql`update work_orders set total=(select coalesce(sum(quantity*unit_price),0) from work_order_items where work_order_id=${workOrderId}) where id=${workOrderId} and company_id=${companyId}`;return NextResponse.json({ok:true})}
 catch{return NextResponse.json({error:'Erro ao excluir item'},{status:500})}
}
