import { NextResponse } from 'next/server'
import { getDb } from '@/lib/db'
import { ensureDb } from '@/lib/bootstrap'
export const dynamic='force-dynamic'
export async function GET(req:Request){try{const companyId=await ensureDb();const sql=getDb();const workOrderId=new URL(req.url).searchParams.get('workOrderId');if(workOrderId){const rows=await sql`select wm.id,wm.quantity,wm.reserved_quantity,m.id material_id,m.name,m.unit,m.stock_quantity,m.min_stock,m.unit_cost,(m.stock_quantity-wm.quantity) projected_stock from work_order_materials wm join materials m on m.id=wm.material_id join work_orders w on w.id=wm.work_order_id where wm.work_order_id=${workOrderId} and w.company_id=${companyId} order by m.name`;return NextResponse.json(rows)}const rows=await sql`select * from materials where company_id=${companyId} order by name`;return NextResponse.json(rows)}catch{return NextResponse.json({error:'Erro ao carregar materiais'},{status:500})}}
export async function POST(req:Request){try{const companyId=await ensureDb();const sql=getDb();const b=await req.json();if(b.workOrderId&&b.materialId){const os=await sql`select id from work_orders where id=${b.workOrderId} and company_id=${companyId}`;if(!os.length)return NextResponse.json({error:'OS não encontrada'},{status:404});const mat=await sql`select id from materials where id=${b.materialId} and company_id=${companyId}`;if(!mat.length)return NextResponse.json({error:'Material inválido'},{status:400});const q=Math.max(Number(b.quantity)||0,0);const rows=await sql`insert into work_order_materials(work_order_id,material_id,quantity) values(${b.workOrderId},${b.materialId},${q}) on conflict(work_order_id,material_id) do update set quantity=excluded.quantity returning *`;return NextResponse.json(rows[0],{status:201})}if(!String(b.name||'').trim())return NextResponse.json({error:'Nome obrigatório'},{status:400});const rows=await sql`insert into materials(company_id,name,unit,stock_quantity,min_stock,unit_cost) values(${companyId},${String(b.name).trim()},${b.unit||'un'},${Number(b.stockQuantity)||0},${Number(b.minStock)||0},${Number(b.unitCost)||0}) on conflict(company_id,name) do update set unit=excluded.unit,stock_quantity=excluded.stock_quantity,min_stock=excluded.min_stock,unit_cost=excluded.unit_cost returning *`;return NextResponse.json(rows[0],{status:201})}catch{return NextResponse.json({error:'Erro ao salvar material'},{status:500})}}

export async function PATCH(req:Request){try{const companyId=await ensureDb();const sql=getDb();const b=await req.json();if(!b.id)return NextResponse.json({error:'Material obrigatório'},{status:400});const before=await sql`select stock_quantity,unit_cost from materials where id=${b.id} and company_id=${companyId} limit 1`;if(!before.length)return NextResponse.json({error:'Material não encontrado'},{status:404});const stock=Math.max(Number(b.stockQuantity)||0,0),cost=Math.max(Number(b.unitCost)||0,0),delta=stock-Number(before[0].stock_quantity||0);const rows=await sql`update materials set name=coalesce(nullif(${String(b.name||'').trim()},''),name),unit=coalesce(nullif(${String(b.unit||'').trim()},''),unit),stock_quantity=${stock},min_stock=${Math.max(Number(b.minStock)||0,0)},unit_cost=${cost} where id=${b.id} and company_id=${companyId} returning *`;if(delta!==0)await sql`insert into inventory_movements(company_id,material_id,movement_type,quantity,unit_cost) values(${companyId},${b.id},'adjustment',${delta},${cost})`;return NextResponse.json(rows[0])}catch{return NextResponse.json({error:'Erro ao atualizar material'},{status:500})}}

export async function DELETE(req:Request){try{const companyId=await ensureDb();const sql=getDb();const b=await req.json();if(!b.id)return NextResponse.json({error:'Material obrigatório'},{status:400});const used=await sql`select 1 from work_order_materials wm join work_orders w on w.id=wm.work_order_id where wm.material_id=${b.id} and w.company_id=${companyId} limit 1`;const recipe=await sql`select 1 from service_catalog_materials scm join materials m on m.id=scm.material_id where scm.material_id=${b.id} and m.company_id=${companyId} limit 1`;if(used.length||recipe.length)return NextResponse.json({error:'Material está vinculado a OS ou ficha técnica e não pode ser excluído.'},{status:409});const rows=await sql`delete from materials where id=${b.id} and company_id=${companyId} returning id`;if(!rows.length)return NextResponse.json({error:'Material não encontrado'},{status:404});return NextResponse.json({ok:true})}catch{return NextResponse.json({error:'Erro ao excluir material'},{status:500})}}
